

CREATE USER IF NOT EXISTS 'mavmw'@'localhost'
	IDENTIFIED WITH 'mysql_native_password' AS '*DB3B2BA694D038846A741FFF90AF3F9F2AC76AE0'
	REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, SHOW VIEW, EVENT, TRIGGER
	ON `mav%mw%`.*
	TO 'mavmw'@'localhost';
GRANT ALL PRIVILEGES
	ON *.* 
	TO 'mavmw'@'localhost' WITH GRANT OPTION;


DROP USER IF EXISTS 'readonly';
CREATE USER 'readonly' @ '%'
	IDENTIFIED WITH 'mysql_native_password' AS '*15654ECA9E11A9992C0F6DA8B76E5EBBC44567FC'
	REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK;
GRANT USAGE ON *.* TO 'readonly'@'%';
GRANT SELECT, CREATE TEMPORARY TABLES, EXECUTE, SHOW VIEW
	ON `mav%mw%`.*
	TO 'readonly'@'%';
	
CREATE USER IF NOT EXISTS 'dev'@'%'
	IDENTIFIED WITH 'mysql_native_password' AS '*124B957EA9C30DCEA56A20FBD6EE4549AA0F157F'
	REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK;
GRANT USAGE ON *.* TO 'dev'@'%';
GRANT ALL PRIVILEGES
	ON *.*
	TO 'dev'@'%';